/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import io.github.bonigarcia.wdm.*;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.*;
import org.openqa.selenium.remote.*;
import org.openqa.selenium.support.ui.*;

import java.time.*;

class LibraryTest {
    public WebDriver driver;

    @BeforeAll
    public static void setDriver() {
        WebDriverManager.chromedriver().setup();
    }

    @BeforeEach
    public void setup() {
        driver = new ChromeDriver();
        driver.get("https://www.selenium.dev/selenium/web/web-form.html");
        driver.manage().window().maximize();
        String title = driver.getTitle();
        assertEquals("Web form", title);
        driver.manage().timeouts().implicitlyWait(Duration.ofMillis(10000));
    }

    @AfterEach
    public void quit() {
        driver.quit();
    }

    @Test
    public void fillForm() {

        WebElement textBox = driver.findElement(By.name("my-text"));
        WebElement password = driver.findElement(By.name("my-password"));
        WebElement textArea = driver.findElement(By.name("my-textarea"));
        Select optionSelect = new Select(driver.findElement(By.name("my-select")));
        WebElement check1 = driver.findElement(By.id("my-check-1"));
        WebElement check2 = driver.findElement(By.id("my-check-2"));
        WebElement submitButton = driver.findElement(By.cssSelector("button"));
        textBox.sendKeys("Selenium");
        password.sendKeys("123456");
        textArea.sendKeys("I am testing with selenium over chrome browser");
        optionSelect.selectByIndex(1);
        check1.click();
        check2.click();
        submitButton.click();
        WebElement message = driver.findElement(By.id("message"));
        String value = message.getText();
        assertEquals("Received!", value);
    }

}
